# Generated by the Release workflow in swissonid/hourglass-rs. Edit that,
# not this: a hand-edit here is overwritten by the next release.
class Hourglass < Formula
  desc "Working-hours, absence and Swiss-public-holiday tracking"
  homepage "https://github.com/swissonid/homebrew-hourglass"
  license "BUSL-1.1"

  # No `version` stanza: brew reads it out of the URL, and two places to state
  # one number is one place for them to disagree.

  on_macos do
    on_arm do
      url "https://github.com/swissonid/homebrew-hourglass/releases/download/v0.1.1/hourglass-0.1.1-aarch64-apple-darwin.tar.gz"
      sha256 "57184636c2b17016642baead5546e54c73ae8ca20c8565ef0d2def3b28e4f668"
    end
    on_intel do
      url "https://github.com/swissonid/homebrew-hourglass/releases/download/v0.1.1/hourglass-0.1.1-x86_64-apple-darwin.tar.gz"
      sha256 "b153eff66a5a359081ac22098a50305c6bfc11fc8ebfe0f2590ae747edbdec62"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/swissonid/homebrew-hourglass/releases/download/v0.1.1/hourglass-0.1.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "cfe7ff20436704c45fb9bd524fcd982c523facf61e25d46f4d44aaec0270dc47"
    end
  end

  def install
    bin.install "hourglass"
  end

  test do
    # The binary knows the tag it was built from, so this checks that the
    # download matched the formula rather than merely that something
    # executable landed.
    assert_match "hourglass #{version}", shell_output("#{bin}/hourglass --version")
  end
end
